### ISSUE TITLE
The login boxes do not scale for fullscreen, making it look slightly odd

### ISSUE THREAD

**Issue by MrAttoAttoAtto** [bhuvan21/arx-noctis#10]
See layout: https://imgur.com/a/I5pPajq

**Comment by bhuvan21** [comment]
The link is appreciated
I believe the issue is now fixed, but I won't mark this as closed until the next build is live, to be sure

**Comment by MrAttoAttoAtto** [comment]
I think that’s good practice for all issues btw

**Comment by bhuvan21** [comment]
noted, and will be done for issues down the line, but stuff like scaling can be especially dodgy in testing

**Comment by bhuvan21** [comment]
looks to be fixed, reopen if you still experience oddness
