### ISSUE TITLE
Multiple accounts with the same username can be created

### ISSUE THREAD

**Issue by MrAttoAttoAtto** [bhuvan21/arx-noctis#11]

**Comment by bhuvan21** [comment]
With the same email address used? I don't think this is possible

**Comment by MrAttoAttoAtto** [comment]
Not the same email, same name

**Comment by bhuvan21** [comment]
That's correct
The character's name isn't something that I think neeeeeds to be unique, since characters won't be interacting directly with each other.

**Comment by MrAttoAttoAtto** [comment]
So there’s no MP?

**Comment by bhuvan21** [comment]
Multiplayer gameplay isn't really something I have in mind
If there will be any, it definitely won't be in the MMORPG style
The only multiplayer situation I have in mind where characters having the same name could be an issue is on leaderboards

**Comment by MrAttoAttoAtto** [comment]
Exactly

**Comment by bhuvan21** [comment]
yup
